services:
  miplay:
    image: ghcr.io/juneix/miplay2:latest
    # image: docker.1ms.run/juneix/miplay2:latest  # 毫秒镜像加速
    container_name: miplay
    network_mode: host
    restart: unless-stopped
    environment:
      WEB_PORT: 8820
    volumes:
      - ./conf:/app/conf